### ISSUE TITLE
Woodcrafter and related Wood Workshops

### ISSUE THREAD

**Issue by ChrisThirtle** [Modified-MW-DF/modified-MDF#8]
The woodcrafter and its various racial derivative workshops (all the buildings that make wood furniture from wood blocks) used to be an efficient means of producing wood items from wood, using half as much materials whenever combined with a wood splitting block, which made 4 blocks of wood from 1 log.
At some point, the wood splitting block was changed to produce only 2 blocks of wood per log, but the woodcrafter and co. were not changed to use only 1 block of wood per furniture item.
If this is a balance issue and we would like to return the woodcrafter and such to their former position of highly-efficient crafting buildings, the raws simply need to change a bit.
If it's staying as-is, the manual needs to be significantly altered in this regard.

**Comment by Amostubal** [comment]
I thought it was 1 log=1 plank at the carpenter. So the wood splitter producing 2 planks from 1 log, with an additional 1 at 50% was more efficiently.

**Comment by Amostubal** [comment]
just dropped them all to 1 plank each...
